version: '3'

services:
  api:
    build: ./thingy-API
    ports:
      - "3900:3900"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://postgres:password@db:5432/thingydb

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
