version: '3'

services:
  
  client:
    build: ./Thingy-Client
    ports:
      - "3899:80"  # Map port 3899 on the host to port 80 in the container
    depends_on:
      - api

  api:
    build: ./Thingy-API
    ports:
      - "3900:3900"
    depends_on:
      - db
      - mosquitto 
    environment:
      - DATABASE_URL=postgres://postgres:password@db:5432/thingydb
      - MQTT_BROKER_URL=${MQTT_BROKER_URL}
    env_file:
      - ./.env

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mosquitto:  
    image: eclipse-mosquitto:latest
    ports:
      - "1883:1883"
    volumes:
      - mosquitto_data:/mosquitto/data
      - mosquitto_log:/mosquitto/log
  
  adminer:
    image: adminer
    ports:
      - "9900:8080"
    depends_on:
      - db

volumes:
  postgres_data:
  mosquitto_data:  
  mosquitto_log:
